#include "MapboxImporterConfig.h"

#include "MapboxAssetGenerator.h"
#include "MapboxLandscapeSettings.h"
#include "MapboxMvtReader.h"

#include "AssetRegistry/AssetRegistryModule.h"
#include "AssetToolsModule.h"
#include "Components/DecalComponent.h"
#include "Components/HierarchicalInstancedStaticMeshComponent.h"
#include "Editor.h"
#include "Engine/DecalActor.h"
#include "Engine/StaticMesh.h"
#include "Engine/Texture2D.h"
#include "Engine/World.h"
#include "EngineUtils.h"
#include "Framework/Notifications/NotificationManager.h"
#include "Misc/MessageDialog.h"
#include "Widgets/Notifications/SNotificationList.h"
#include "FileHelpers.h"
#include "HttpModule.h"
#include "IImageWrapper.h"
#include "IImageWrapperModule.h"
#include "Interfaces/IHttpResponse.h"
#include "Landscape.h"
#include "LandscapeComponent.h"
#include "LandscapeInfo.h"
#include "LandscapeLayerInfoObject.h"
#include "LandscapeProxy.h"
#include "Materials/MaterialInstanceConstant.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "Materials/MaterialInterface.h"
#include "Factories/MaterialInstanceConstantFactoryNew.h"
#include "Misc/PackageName.h"
#include "Modules/ModuleManager.h"
#include "PCGComponent.h"
#include "PCGGraph.h"
#include "UObject/Package.h"
#include "UObject/SavePackage.h"

DEFINE_LOG_CATEGORY_STATIC(LogMapbox, Log, All);

namespace MapboxUI
{
	enum class ESeverity : uint8 { Info, Success, Warning, Error };

	static void Notify(ESeverity Sev, const FString& Title, const FString& Detail = FString(), bool bModal = false)
	{
		const FString Combined = Detail.IsEmpty() ? Title : (Title + TEXT("\n") + Detail);

		switch (Sev)
		{
		case ESeverity::Error:   UE_LOG(LogMapbox, Error,   TEXT("%s"), *Combined); break;
		case ESeverity::Warning: UE_LOG(LogMapbox, Warning, TEXT("%s"), *Combined); break;
		default:                 UE_LOG(LogMapbox, Log,     TEXT("%s"), *Combined); break;
		}

#if WITH_EDITOR
		FNotificationInfo Info(FText::FromString(Title));
		Info.SubText = Detail.IsEmpty() ? FText::GetEmpty() : FText::FromString(Detail);
		Info.bUseLargeFont = false;
		Info.bFireAndForget = true;
		Info.FadeOutDuration = 1.0f;
		Info.ExpireDuration = (Sev == ESeverity::Info) ? 4.f : 10.f;

		TSharedPtr<SNotificationItem> Item = FSlateNotificationManager::Get().AddNotification(Info);
		if (Item.IsValid())
		{
			SNotificationItem::ECompletionState State = SNotificationItem::CS_None;
			switch (Sev)
			{
			case ESeverity::Success: State = SNotificationItem::CS_Success; break;
			case ESeverity::Warning:
			case ESeverity::Error:   State = SNotificationItem::CS_Fail;    break;
			default: break;
			}
			Item->SetCompletionState(State);
		}

		if (bModal)
		{
			FMessageDialog::Open(EAppMsgType::Ok, FText::FromString(Combined));
		}
#endif
	}
}

UMapboxImporterConfig::UMapboxImporterConfig()
{
	// Pure editor authoring object. Seed defaults from project settings; the subsystem owns the live instance.
	const UMapboxLandscapeSettings* Settings = GetDefault<UMapboxLandscapeSettings>();
	if (Settings)
	{
		MetadataStyleId = Settings->DefaultMetadataStyleId;
		bAutoZoom = Settings->bDefaultAutoZoom;
		ZoomLevel = Settings->DefaultZoomLevel;
		TilesPerLandscapeSide = Settings->DefaultTilesPerLandscapeSide;
		MaxLandscapesTotal = Settings->DefaultMaxLandscapesTotal;
		MaxConcurrentRequests = Settings->DefaultMaxConcurrentRequests;
		ZExaggeration = Settings->DefaultZExaggeration;
		bRebaseToSeaLevel = Settings->bDefaultRebaseToSeaLevel;
		SatelliteMode = Settings->DefaultSatelliteMode;
		CenterLatitude = Settings->DefaultCenterLatitude;
		CenterLongitude = Settings->DefaultCenterLongitude;
		RadiusKm = Settings->DefaultRadiusKm;
		LandscapeMasterMaterial = Settings->DefaultLandscapeMasterMaterial;
		bAutoGenerateDefaultAssets = Settings->bDefaultAutoGenerateAssets;
		ScatterPCGGraph = Settings->DefaultScatterPCGGraph;
		bSpawnPCGComponents = Settings->bDefaultSpawnPCGComponents;
		MapboxLayers = Settings->DefaultLayers;
	}

	if (MapboxLayers.IsEmpty())
	{
		EnsureDefaultLayers();
	}
}

UWorld* UMapboxImporterConfig::GetWorld() const
{
	if (GIsEditor && GEditor)
	{
		if (UWorld* W = GEditor->GetEditorWorldContext().World())
		{
			return W;
		}
	}
	return nullptr;
}

#if WITH_EDITOR
bool UMapboxImporterConfig::CanEditChange(const FProperty* InProperty) const
{
	return !bIsFetching && Super::CanEditChange(InProperty);
}
#endif

void UMapboxImporterConfig::EnsureDefaultLayers()
{
	if (!MapboxLayers.IsEmpty()) return;

	auto MakeVectorLayer = [](FName Name, const FString& MvtLayer, const TArray<FString>& Classes,
		float LineWidth, int32 Priority, FLinearColor Tint, bool bScatter = false, float Density = 0.f) -> FMapboxLayerDef
	{
		FMapboxLayerDef L;
		L.LayerName = Name;
		L.MatchMode = EMapboxLayerMatchMode::Vector;
		L.Priority = Priority;
		L.MaterialTint = Tint;
		L.bScatterEnabled = bScatter;
		L.ScatterDensity = Density;

		FMapboxVectorFeatureFilter F;
		F.MvtLayer = MvtLayer;
		F.Classes = Classes;
		F.LineWidthMeters = LineWidth;
		L.VectorFilters.Add(F);
		return L;
	};

	// Polygons (priority highest — buildings/water override everything else)
	FMapboxLayerDef Water = MakeVectorLayer(TEXT("Water"), TEXT("water"), {}, 0.f, 90,
		FLinearColor(0.10f, 0.25f, 0.45f));

	FMapboxLayerDef Building = MakeVectorLayer(TEXT("Buildings"), TEXT("building"), {}, 0.f, 80,
		FLinearColor(0.4f, 0.38f, 0.35f));

	// Airport surfaces
	FMapboxLayerDef Runway = MakeVectorLayer(TEXT("Runway"), TEXT("aeroway"),
		{ TEXT("runway") }, 45.f, 75, FLinearColor(0.18f, 0.18f, 0.20f));

	FMapboxLayerDef Taxiway = MakeVectorLayer(TEXT("Taxiway"), TEXT("aeroway"),
		{ TEXT("taxiway") }, 18.f, 72, FLinearColor(0.22f, 0.22f, 0.22f));

	// Road network — graded by class so highways look different from footpaths
	FMapboxLayerDef Highway = MakeVectorLayer(TEXT("Highway"), TEXT("road"),
		{ TEXT("motorway"), TEXT("motorway_link"), TEXT("trunk"), TEXT("trunk_link") },
		15.f, 60, FLinearColor(0.25f, 0.25f, 0.27f));

	FMapboxLayerDef Primary = MakeVectorLayer(TEXT("PrimaryRoad"), TEXT("road"),
		{ TEXT("primary"), TEXT("primary_link"), TEXT("secondary"), TEXT("secondary_link") },
		10.f, 55, FLinearColor(0.32f, 0.32f, 0.34f));

	FMapboxLayerDef Tertiary = MakeVectorLayer(TEXT("TertiaryRoad"), TEXT("road"),
		{ TEXT("tertiary"), TEXT("tertiary_link"), TEXT("street") },
		7.f, 50, FLinearColor(0.38f, 0.38f, 0.40f));

	FMapboxLayerDef Residential = MakeVectorLayer(TEXT("ResidentialRoad"), TEXT("road"),
		{ TEXT("street_limited"), TEXT("service"), TEXT("track") },
		5.f, 45, FLinearColor(0.45f, 0.45f, 0.47f));

	FMapboxLayerDef Path = MakeVectorLayer(TEXT("Path"), TEXT("road"),
		{ TEXT("path"), TEXT("footway"), TEXT("pedestrian"), TEXT("steps") },
		2.f, 40, FLinearColor(0.55f, 0.48f, 0.35f));

	FMapboxLayerDef Railway = MakeVectorLayer(TEXT("Railway"), TEXT("road"),
		{ TEXT("major_rail"), TEXT("minor_rail"), TEXT("service_rail") },
		4.f, 52, FLinearColor(0.20f, 0.20f, 0.22f));

	// Landuse polygons — drive vegetation scatter
	FMapboxLayerDef Forest = MakeVectorLayer(TEXT("Forest"), TEXT("landuse"),
		{ TEXT("wood"), TEXT("forest") },
		0.f, 30, FLinearColor(0.20f, 0.45f, 0.15f), /*bScatter=*/true, /*density=*/4.f);

	FMapboxLayerDef Park = MakeVectorLayer(TEXT("Park"), TEXT("landuse"),
		{ TEXT("park"), TEXT("pitch"), TEXT("garden") },
		0.f, 28, FLinearColor(0.35f, 0.55f, 0.30f), /*bScatter=*/true, /*density=*/8.f);

	FMapboxLayerDef Industrial = MakeVectorLayer(TEXT("Industrial"), TEXT("landuse"),
		{ TEXT("industrial"), TEXT("commercial"), TEXT("parking") },
		0.f, 25, FLinearColor(0.45f, 0.45f, 0.42f));

	// Color fallback — catches everything else as grass
	FMapboxLayerDef Grass;
	Grass.LayerName = TEXT("Grass");
	Grass.MatchMode = EMapboxLayerMatchMode::Color;
	Grass.TargetColor = FLinearColor(0.55f, 0.70f, 0.30f);
	Grass.MaterialTint = FLinearColor(0.45f, 0.55f, 0.25f);
	Grass.Priority = 10;
	Grass.bScatterEnabled = true;
	Grass.ScatterDensity = 12.f;

	MapboxLayers = { Water, Building, Runway, Taxiway, Highway, Primary, Tertiary,
		Residential, Path, Railway, Forest, Park, Industrial, Grass };
}

void UMapboxImporterConfig::ResetLayersToDefaults()
{
	MapboxLayers.Empty();
	EnsureDefaultLayers();
}

void UMapboxImporterConfig::ClearGeneratedLandscapes()
{
	for (const FMapboxTileResult& Tile : GeneratedLandscapes)
	{
		if (Tile.Landscape && IsValid(Tile.Landscape))
		{
			Tile.Landscape->Destroy();
		}
	}
	GeneratedLandscapes.Reset();
}

void UMapboxImporterConfig::RegenerateDefaultAssets()
{
#if WITH_EDITOR
	TArray<FName> Names;
	for (const FMapboxLayerDef& L : MapboxLayers) { Names.Add(L.LayerName); }
	MapboxAssetGenerator::GetOrCreateDefaultMasterMaterial(Names, /*bForceRecreate=*/true);
	MapboxAssetGenerator::GetOrCreateDefaultScatterGraph();
	UE_LOG(LogMapbox, Log, TEXT("Mapbox default assets regenerated."));
#endif
}

FString UMapboxImporterConfig::GetApiKey()
{
	const UMapboxLandscapeSettings* Settings = GetDefault<UMapboxLandscapeSettings>();
	return Settings ? Settings->ApiKey : FString();
}

void UMapboxImporterConfig::FixExistingLandscapeMaterials()
{
#if WITH_EDITOR
	// Build the working set: in-memory GeneratedLandscapes plus any "MapboxLandscape_C*" actors
	// in the current editor world. The level scan is what makes this work after editor restart
	// (the importer config is transient and forgets refs between sessions).
	TSet<TObjectPtr<ALandscape>> Working;
	for (const FMapboxTileResult& T : GeneratedLandscapes)
	{
		if (IsValid(T.Landscape)) Working.Add(T.Landscape);
	}

	UWorld* World = GetWorld();
	if (World)
	{
		for (TActorIterator<ALandscape> It(World); It; ++It)
		{
			ALandscape* L = *It;
			if (!IsValid(L)) continue;
			const FString Label = L->GetActorLabel();
			const FString Name = L->GetName();
			if (Label.StartsWith(TEXT("MapboxLandscape_")) || Name.StartsWith(TEXT("MapboxLandscape_")))
			{
				Working.Add(L);
			}
		}
	}

	if (Working.IsEmpty())
	{
		MapboxUI::Notify(MapboxUI::ESeverity::Warning,
			TEXT("Mapbox: no landscapes to fix."),
			TEXT("Couldn't find any 'MapboxLandscape_C*' actors in this level. If the landscapes were renamed, rename one back to that prefix and try again, or just re-fetch."));
		return;
	}

	// 1. Rebuild master material with the latest UV graph.
	TArray<FName> Names;
	for (const FMapboxLayerDef& L : MapboxLayers) { Names.Add(L.LayerName); }
	UMaterialInterface* Master = MapboxAssetGenerator::GetOrCreateDefaultMasterMaterial(Names, /*bForceRecreate=*/true);
	if (!Master)
	{
		MapboxUI::Notify(MapboxUI::ESeverity::Error,
			TEXT("Mapbox: failed to rebuild master material."),
			TEXT("Check the Output Log."));
		return;
	}

	// 2. Recompute each landscape's origin/size from its actor transform, rebuild its MIC, reassign.
	int32 Fixed = 0;
	int32 ChunkIdx = 0;
	for (ALandscape* Landscape : Working)
	{
		if (!IsValid(Landscape)) continue;

		const FVector ChunkOrigin = Landscape->GetActorLocation();
		const FBox Bounds = Landscape->GetComponentsBoundingBox(true);
		const double WorldSizeX = Bounds.Max.X - Bounds.Min.X;
		const double WorldSizeY = Bounds.Max.Y - Bounds.Min.Y;
		const double WorldSize = FMath::Max(WorldSizeX, WorldSizeY);
		if (WorldSize < 100.0)
		{
			UE_LOG(LogMapbox, Warning, TEXT("Mapbox: %s has unexpectedly small bounds (%.0f cm), skipping."),
				*Landscape->GetActorLabel(), WorldSize);
			continue;
		}

		// Try to derive ChunkX/ChunkY from the actor name; fall back to a counter so each MIC gets a unique path.
		int32 ChunkX = ChunkIdx, ChunkY = 0;
		{
			const FString Name = Landscape->GetName();
			int32 UnderscoreC = INDEX_NONE;
			if (Name.FindLastChar(TCHAR('C'), UnderscoreC))
			{
				const FString TailFromC = Name.Mid(UnderscoreC + 1);
				TArray<FString> Parts;
				TailFromC.ParseIntoArray(Parts, TEXT("_"), true);
				if (Parts.Num() >= 2)
				{
					ChunkX = FCString::Atoi(*Parts[0]);
					ChunkY = FCString::Atoi(*Parts[1]);
				}
			}
		}

		// Re-resolve the chunk's satellite texture. Looking it up through the current MIC fails after
		// a forced master rebuild (the param table just changed), so we go straight to the asset on disk.
		// Files were saved as /Game/MapboxLandscape/Textures/T_MapboxSat_C{X}_{Y}_Z{Z}; zoom is unknown
		// here, so we scan the folder for any matching X/Y.
		UTexture2D* SatTexture = nullptr;
		{
			const FString Prefix = FString::Printf(TEXT("T_MapboxSat_C%d_%d_Z"), ChunkX, ChunkY);

			IAssetRegistry& AssetRegistry = FModuleManager::LoadModuleChecked<FAssetRegistryModule>("AssetRegistry").Get();
			TArray<FAssetData> AssetsInFolder;
			AssetRegistry.GetAssetsByPath(FName(TEXT("/Game/MapboxLandscape/Textures")), AssetsInFolder, /*bRecursive=*/false);

			for (const FAssetData& Asset : AssetsInFolder)
			{
				if (Asset.AssetName.ToString().StartsWith(Prefix))
				{
					SatTexture = Cast<UTexture2D>(Asset.GetAsset());
					if (SatTexture) break;
				}
			}

			if (!SatTexture)
			{
				UE_LOG(LogMapbox, Warning, TEXT("Mapbox: %s has no matching T_MapboxSat_C%d_%d_Z* in /Game/MapboxLandscape/Textures/. Material will render with default texture."),
					*Landscape->GetActorLabel(), ChunkX, ChunkY);
			}
		}

		UMaterialInstanceConstant* MIC = CreateMaterialInstanceForChunk(
			Master, SatTexture, ChunkX, ChunkY, ChunkOrigin, WorldSize);
		if (MIC)
		{
			Landscape->LandscapeMaterial = MIC;
			Landscape->PostEditChange();
			Landscape->ReregisterAllComponents();
			++Fixed;
		}
		++ChunkIdx;
	}

	MapboxUI::Notify(MapboxUI::ESeverity::Success,
		FString::Printf(TEXT("Mapbox: fixed materials on %d landscape(s)."), Fixed));
#endif
}

void UMapboxImporterConfig::ResetFromProjectSettings()
{
	const UMapboxLandscapeSettings* Settings = GetDefault<UMapboxLandscapeSettings>();
	if (!Settings)
	{
		UE_LOG(LogMapbox, Warning, TEXT("Mapbox: project settings not available."));
		return;
	}

	Modify();
	MetadataStyleId = Settings->DefaultMetadataStyleId;
	bAutoZoom = Settings->bDefaultAutoZoom;
	ZoomLevel = Settings->DefaultZoomLevel;
	TilesPerLandscapeSide = Settings->DefaultTilesPerLandscapeSide;
	MaxLandscapesTotal = Settings->DefaultMaxLandscapesTotal;
	MaxConcurrentRequests = Settings->DefaultMaxConcurrentRequests;
	ZExaggeration = Settings->DefaultZExaggeration;
	bRebaseToSeaLevel = Settings->bDefaultRebaseToSeaLevel;
	SatelliteMode = Settings->DefaultSatelliteMode;
	CenterLatitude = Settings->DefaultCenterLatitude;
	CenterLongitude = Settings->DefaultCenterLongitude;
	RadiusKm = Settings->DefaultRadiusKm;
	LandscapeMasterMaterial = Settings->DefaultLandscapeMasterMaterial;
	bAutoGenerateDefaultAssets = Settings->bDefaultAutoGenerateAssets;
	ScatterPCGGraph = Settings->DefaultScatterPCGGraph;
	bSpawnPCGComponents = Settings->bDefaultSpawnPCGComponents;
	MapboxLayers = Settings->DefaultLayers;

#if WITH_EDITOR
	PostEditChange();
#endif
	UE_LOG(LogMapbox, Log, TEXT("Mapbox: actor reset from project settings."));
}

// ----- Slippy-map math --------------------------------------------------------

static double TileXToLon(double X, int32 Z)
{
	return X / FMath::Pow(2.0, Z) * 360.0 - 180.0;
}

static double TileYToLat(double Y, int32 Z)
{
	const double N = PI - 2.0 * PI * Y / FMath::Pow(2.0, Z);
	return FMath::RadiansToDegrees(FMath::Atan(FMath::Sinh(N)));
}

static int32 LonToTileX(double Lon, int32 Z)
{
	return (int32)FMath::Floor((Lon + 180.0) / 360.0 * FMath::Pow(2.0, Z));
}

static int32 LatToTileY(double Lat, int32 Z)
{
	const double R = FMath::DegreesToRadians(Lat);
	return (int32)FMath::Floor((1.0 - FMath::Loge(FMath::Tan(R) + 1.0 / FMath::Cos(R)) / PI) / 2.0 * FMath::Pow(2.0, Z));
}

static double MetersPerTileSide(double Lat, int32 Z)
{
	const double EarthCirc = 40075016.686;
	return EarthCirc * FMath::Cos(FMath::DegreesToRadians(Lat)) / FMath::Pow(2.0, Z);
}

// Returns true if any layer requires Mapbox vector tiles (one with MatchMode != Color and at least one filter).
static bool LayersNeedVectorTiles(const TArray<FMapboxLayerDef>& Layers)
{
	for (const FMapboxLayerDef& L : Layers)
	{
		if (L.MatchMode != EMapboxLayerMatchMode::Color && !L.VectorFilters.IsEmpty())
		{
			return true;
		}
	}
	return false;
}

// ----- Bounding box resolution ------------------------------------------------

void UMapboxImporterConfig::ResolveBoundingBox(double& OutNorth, double& OutSouth, double& OutEast, double& OutWest) const
{
	OutNorth = North; OutSouth = South; OutEast = East; OutWest = West;

	if (CoordinateMode == ECoordinateMode::CenterRadius)
	{
		const double DLat = RadiusKm / 111.32;
		const double DLng = RadiusKm / (111.32 * FMath::Cos(FMath::DegreesToRadians(CenterLatitude)));
		OutNorth = CenterLatitude + DLat;
		OutSouth = CenterLatitude - DLat;
		OutEast = CenterLongitude + DLng;
		OutWest = CenterLongitude - DLng;
	}
	else if (CoordinateMode == ECoordinateMode::ToolString)
	{
		TArray<FString> Parts;
		FString Clean = CoordinateString.Replace(TEXT(" "), TEXT(","));
		Clean.ParseIntoArray(Parts, TEXT(","), true);
		TArray<double> Vals;
		for (const FString& P : Parts) { Vals.Add(FCString::Atod(*P.TrimStartAndEnd())); }
		if (Vals.Num() < 4) return;

		// Heuristic: if any even-index value exceeds 90, evens are lng; otherwise assume evens=lat
		bool bEvenAreLat = true;
		for (int32 i = 0; i < Vals.Num(); i += 2)
		{
			if (FMath::Abs(Vals[i]) > 90.0) { bEvenAreLat = false; break; }
		}
		TArray<double> Lats, Lngs;
		for (int32 i = 0; i < Vals.Num(); ++i)
		{
			if ((i % 2 == 0) == bEvenAreLat) Lats.Add(Vals[i]);
			else Lngs.Add(Vals[i]);
		}
		if (Lats.Num() == 0 || Lngs.Num() == 0) return;

		OutSouth = OutNorth = Lats[0];
		OutWest = OutEast = Lngs[0];
		for (double V : Lats) { OutSouth = FMath::Min(OutSouth, V); OutNorth = FMath::Max(OutNorth, V); }
		for (double V : Lngs) { OutWest = FMath::Min(OutWest, V); OutEast = FMath::Max(OutEast, V); }
	}
}

int32 UMapboxImporterConfig::PickAutoZoom(double DegreesPerSide) const
{
	// Target around TilesPerLandscapeSide * MaxLandscapesTotal^0.5 tiles per side.
	const double TargetTiles = FMath::Sqrt((double)MaxLandscapesTotal) * (double)TilesPerLandscapeSide;
	// At zoom Z, tile_size_deg = 360 / 2^Z (in longitude). Solve 2^Z = TargetTiles * 360/DegreesPerSide.
	const double DesiredPow2 = TargetTiles * 360.0 / FMath::Max(DegreesPerSide, 1e-6);
	int32 Z = FMath::Clamp((int32)FMath::FloorToInt(FMath::Loge(DesiredPow2) / FMath::Loge(2.0)), 8, 16);
	return Z;
}

// ----- Tile enumeration & download ------------------------------------------

void UMapboxImporterConfig::EnumerateTiles(double N, double S, double E, double W, int32 Zoom)
{
	MinTileX = LonToTileX(W, Zoom);
	MaxTileX = LonToTileX(E, Zoom);
	MinTileY = LatToTileY(N, Zoom);
	MaxTileY = LatToTileY(S, Zoom);

	if (MinTileX > MaxTileX) Swap(MinTileX, MaxTileX);
	if (MinTileY > MaxTileY) Swap(MinTileY, MaxTileY);

	PendingDownloadQueue.Reset();
	CompletedBlobs.Reset();

	// One coord per (X, Y); StartNextDownloads issues all 3 (height/meta/satellite) per coord.
	for (int32 X = MinTileX; X <= MaxTileX; ++X)
	{
		for (int32 Y = MinTileY; Y <= MaxTileY; ++Y)
		{
			PendingDownloadQueue.Push({ X, Y, Zoom });
		}
	}

	const bool bNeedVector = LayersNeedVectorTiles(MapboxLayers);
	TotalExpectedBlobs = (MaxTileX - MinTileX + 1) * (MaxTileY - MinTileY + 1) *
		(2 + (SatelliteMode != EMapboxSatelliteMode::None ? 1 : 0) + (bNeedVector ? 1 : 0));

	// Build chunks
	Chunks.Reset();
	const int32 TilesXAll = MaxTileX - MinTileX + 1;
	const int32 TilesYAll = MaxTileY - MinTileY + 1;
	const int32 Step = FMath::Max(1, TilesPerLandscapeSide);
	for (int32 cy = 0; cy < TilesYAll; cy += Step)
	{
		for (int32 cx = 0; cx < TilesXAll; cx += Step)
		{
			FLandscapeChunk C;
			C.ChunkX = cx / Step;
			C.ChunkY = cy / Step;
			C.MinTileX = MinTileX + cx;
			C.MinTileY = MinTileY + cy;
			C.TilesX = FMath::Min(Step, TilesXAll - cx);
			C.TilesY = FMath::Min(Step, TilesYAll - cy);
			Chunks.Add(C);
		}
	}
}

void UMapboxImporterConfig::FetchLandscape()
{
	if (bIsFetching)
	{
		MapboxUI::Notify(MapboxUI::ESeverity::Warning,
			TEXT("Mapbox: a fetch is already running."),
			TEXT("Wait for it to finish (watch the toasts) before starting another."));
		return;
	}
	if (GetApiKey().IsEmpty())
	{
		MapboxUI::Notify(MapboxUI::ESeverity::Error,
			TEXT("Mapbox API key is empty."),
			TEXT("Open Project Settings > Plugins > Mapbox Landscape and paste your Mapbox access token into 'Api Key'."),
			/*bModal=*/true);
		return;
	}

	EnsureDefaultLayers();
	bIsFetching = true;
	InFlightRequests = 0;

	double N, S, E, W;
	ResolveBoundingBox(N, S, E, W);
	if (N <= S || E <= W)
	{
		MapboxUI::Notify(MapboxUI::ESeverity::Error,
			TEXT("Mapbox: invalid bounding box."),
			FString::Printf(TEXT("Got N=%.5f S=%.5f E=%.5f W=%.5f. North must be > South and East must be > West."), N, S, E, W),
			/*bModal=*/true);
		FinishFetch();
		return;
	}

	const double DegSide = FMath::Max(N - S, (E - W) * FMath::Cos(FMath::DegreesToRadians((N + S) * 0.5)));
	ResolvedZoom = bAutoZoom ? PickAutoZoom(DegSide) : FMath::Clamp(ZoomLevel, 8, 18);

	EnumerateTiles(N, S, E, W, ResolvedZoom);

	const int32 TotalTiles = (MaxTileX - MinTileX + 1) * (MaxTileY - MinTileY + 1);
	const int32 LandscapeCount = Chunks.Num();
	UE_LOG(LogMapbox, Log, TEXT("Mapbox: BBox N=%.5f S=%.5f E=%.5f W=%.5f"), N, S, E, W);
	UE_LOG(LogMapbox, Log, TEXT("Mapbox: zoom=%d, tiles=%d, landscapes=%d (chunks of %d^2 tiles)"),
		ResolvedZoom, TotalTiles, LandscapeCount, TilesPerLandscapeSide);
	MapboxUI::Notify(MapboxUI::ESeverity::Info,
		FString::Printf(TEXT("Mapbox: fetching %d tiles at zoom %d…"), TotalTiles, ResolvedZoom),
		FString::Printf(TEXT("Will produce %d landscape actor(s)."), LandscapeCount));

	if (LandscapeCount > MaxLandscapesTotal)
	{
		MapboxUI::Notify(MapboxUI::ESeverity::Error,
			FString::Printf(TEXT("Mapbox: aborting — would create %d landscape tiles (limit %d)."), LandscapeCount, MaxLandscapesTotal),
			FString::Printf(TEXT("Pick one of:\n  • Reduce Radius Km (currently covers ~%dx%d tiles at zoom %d)\n  • Turn off Auto Zoom and pick a lower Zoom Level\n  • Increase Tiles Per Landscape Side (currently %d)\n  • Raise Max Landscapes Total above %d"),
				(MaxTileX - MinTileX + 1), (MaxTileY - MinTileY + 1), ResolvedZoom, TilesPerLandscapeSide, MaxLandscapesTotal),
			/*bModal=*/true);
		FinishFetch();
		return;
	}

	if (TotalTiles == 0)
	{
		MapboxUI::Notify(MapboxUI::ESeverity::Error,
			TEXT("Mapbox: no tiles in range."),
			TEXT("Check that your coordinates / bounding box are valid."),
			/*bModal=*/true);
		FinishFetch();
		return;
	}

	StartNextDownloads();
}

void UMapboxImporterConfig::StartNextDownloads()
{
	const bool bNeedVector = LayersNeedVectorTiles(MapboxLayers);

	while (InFlightRequests < MaxConcurrentRequests && PendingDownloadQueue.Num() > 0)
	{
		FTileCoord Coord = PendingDownloadQueue.Pop(EAllowShrinking::No);
		StartRequest(Coord, ETileKind::Height);
		StartRequest(Coord, ETileKind::Metadata);
		if (SatelliteMode != EMapboxSatelliteMode::None)
		{
			StartRequest(Coord, ETileKind::Satellite);
		}
		if (bNeedVector)
		{
			StartRequest(Coord, ETileKind::Vector);
		}
	}

	// If nothing pending and nothing in flight, but we expected blobs, finalize.
	if (PendingDownloadQueue.Num() == 0 && InFlightRequests == 0)
	{
		OnAllTilesDownloaded();
	}
}

void UMapboxImporterConfig::StartRequest(const FTileCoord& Coord, ETileKind Kind)
{
	FString Url;
	switch (Kind)
	{
	case ETileKind::Height:
		Url = FString::Printf(TEXT("https://api.mapbox.com/v4/mapbox.terrain-rgb/%d/%d/%d.pngraw?access_token=%s"),
			Coord.Z, Coord.X, Coord.Y, *GetApiKey());
		break;
	case ETileKind::Metadata:
		Url = FString::Printf(TEXT("https://api.mapbox.com/styles/v1/%s/tiles/%d/%d/%d?access_token=%s"),
			*MetadataStyleId, Coord.Z, Coord.X, Coord.Y, *GetApiKey());
		break;
	case ETileKind::Satellite:
		Url = FString::Printf(TEXT("https://api.mapbox.com/v4/mapbox.satellite/%d/%d/%d.png?access_token=%s"),
			Coord.Z, Coord.X, Coord.Y, *GetApiKey());
		break;
	case ETileKind::Vector:
		Url = FString::Printf(TEXT("https://api.mapbox.com/v4/mapbox.mapbox-streets-v8/%d/%d/%d.mvt?access_token=%s"),
			Coord.Z, Coord.X, Coord.Y, *GetApiKey());
		break;
	}

	TSharedRef<IHttpRequest, ESPMode::ThreadSafe> Request = FHttpModule::Get().CreateRequest();
	Request->OnProcessRequestComplete().BindUObject(this, &UMapboxImporterConfig::OnTileResponse, Coord, Kind);
	Request->SetURL(Url);
	Request->SetVerb(TEXT("GET"));
	Request->ProcessRequest();
	++InFlightRequests;
}

static FString KeyFor(int32 X, int32 Y, UMapboxImporterConfig::ETileKind Kind)
{
	const TCHAR* K = TEXT("h");
	if (Kind == UMapboxImporterConfig::ETileKind::Metadata) K = TEXT("m");
	else if (Kind == UMapboxImporterConfig::ETileKind::Satellite) K = TEXT("s");
	else if (Kind == UMapboxImporterConfig::ETileKind::Vector) K = TEXT("v");
	return FString::Printf(TEXT("%s_%d_%d"), K, X, Y);
}

void UMapboxImporterConfig::OnTileResponse(FHttpRequestPtr Request, FHttpResponsePtr Response, bool bSuccess, FTileCoord Coord, ETileKind Kind)
{
	--InFlightRequests;
	FTileBlob Blob;
	Blob.Coord = Coord;
	Blob.Kind = Kind;
	if (bSuccess && Response.IsValid() && Response->GetResponseCode() < 400)
	{
		Blob.Bytes = Response->GetContent();
		Blob.bOk = Blob.Bytes.Num() > 0;
	}
	if (!Blob.bOk)
	{
		UE_LOG(LogMapbox, Warning, TEXT("Mapbox: tile fetch failed kind=%d at %d/%d code=%d"),
			(int32)Kind, Coord.X, Coord.Y, Response.IsValid() ? Response->GetResponseCode() : 0);
	}
	CompletedBlobs.Add(KeyFor(Coord.X, Coord.Y, Kind), MoveTemp(Blob));

	StartNextDownloads();
}

// ----- Image decoding helpers ------------------------------------------------

static bool DecodeTileToRGBA(const TArray<uint8>& Bytes, TArray<uint8>& OutRGBA, int32& OutW, int32& OutH)
{
	IImageWrapperModule& Module = FModuleManager::LoadModuleChecked<IImageWrapperModule>("ImageWrapper");
	EImageFormat Format = EImageFormat::PNG;
	if (Bytes.Num() > 4 && Bytes[0] == 0xFF && Bytes[1] == 0xD8) Format = EImageFormat::JPEG;
	else if (Bytes.Num() > 4 && Bytes[0] == 'R' && Bytes[1] == 'I' && Bytes[2] == 'F' && Bytes[3] == 'F') Format = EImageFormat::PNG; // fallback

	TSharedPtr<IImageWrapper> Wrapper = Module.CreateImageWrapper(Format);
	if (!Wrapper.IsValid() || !Wrapper->SetCompressed(Bytes.GetData(), Bytes.Num()))
	{
		return false;
	}
	OutW = Wrapper->GetWidth();
	OutH = Wrapper->GetHeight();
	return Wrapper->GetRaw(ERGBFormat::RGBA, 8, OutRGBA);
}

uint16 UMapboxImporterConfig::DecodeHeight(uint8 R, uint8 G, uint8 B) const
{
	// Mapbox Terrain-RGB: meters = -10000 + (R*256*256 + G*256 + B) * 0.1
	// We do not encode here; this entry point is unused in the new pipeline (we decode floats first).
	const float Meters = -10000.0f + (R * 65536.0f + G * 256.0f + B) * 0.1f;
	return (uint16)FMath::Clamp(FMath::RoundToInt(Meters), 0, 65535);
}

static float DecodeHeightMeters(uint8 R, uint8 G, uint8 B)
{
	return -10000.0f + (R * 65536.0f + G * 256.0f + B) * 0.1f;
}

// ----- Pixel classification --------------------------------------------------

static void RGBToHSV(const FLinearColor& In, float& OutH, float& OutS, float& OutV)
{
	const float R = In.R; const float G = In.G; const float B = In.B;
	const float Cmax = FMath::Max(R, FMath::Max(G, B));
	const float Cmin = FMath::Min(R, FMath::Min(G, B));
	const float Delta = Cmax - Cmin;
	OutV = Cmax;
	OutS = Cmax > 0.f ? Delta / Cmax : 0.f;
	if (Delta < 1e-5f) { OutH = 0.f; return; }
	float H;
	if (Cmax == R)      H = (G - B) / Delta;
	else if (Cmax == G) H = 2.f + (B - R) / Delta;
	else                H = 4.f + (R - G) / Delta;
	H /= 6.f;
	if (H < 0.f) H += 1.f;
	OutH = H;
}

int32 UMapboxImporterConfig::ClassifyPixel(const FColor& Pixel) const
{
	const FLinearColor Src(Pixel);
	float SrcH, SrcS, SrcV;
	RGBToHSV(Src, SrcH, SrcS, SrcV);

	int32 BestIdx = INDEX_NONE;
	float BestScore = MAX_FLT;
	int32 BestPriority = -1;

	for (int32 i = 0; i < MapboxLayers.Num(); ++i)
	{
		const FMapboxLayerDef& L = MapboxLayers[i];
		float Score = MAX_FLT;
		if (L.ColorSpace == EMapboxColorSpace::RGB)
		{
			const FLinearColor D = Src - L.TargetColor;
			Score = FMath::Sqrt(D.R * D.R + D.G * D.G + D.B * D.B);
			if (Score > L.RGBTolerance) continue;
		}
		else
		{
			float TH, TS, TV;
			RGBToHSV(L.TargetColor, TH, TS, TV);
			float Hd = FMath::Abs(SrcH - TH);
			Hd = FMath::Min(Hd, 1.f - Hd);
			const float Sd = FMath::Abs(SrcS - TS);
			const float Vd = FMath::Abs(SrcV - TV);
			if (Hd > L.HueTolerance || Sd > L.SatTolerance || Vd > L.ValTolerance) continue;
			Score = Hd * 3.f + Sd + Vd;
		}

		if (L.Priority > BestPriority || (L.Priority == BestPriority && Score < BestScore))
		{
			BestPriority = L.Priority;
			BestScore = Score;
			BestIdx = i;
		}
	}
	return BestIdx;
}

// ----- Texture asset save ----------------------------------------------------

UTexture2D* UMapboxImporterConfig::SaveTransientToAsset(const TArray<FColor>& Pixels, int32 W, int32 H, const FString& AssetName) const
{
#if WITH_EDITOR
	if (Pixels.Num() != W * H) return nullptr;

	const FString PackagePath = FString::Printf(TEXT("/Game/MapboxLandscape/Textures/%s"), *AssetName);
	UPackage* Package = CreatePackage(*PackagePath);
	if (!Package) return nullptr;
	Package->FullyLoad();

	UTexture2D* Texture = NewObject<UTexture2D>(Package, *AssetName, RF_Public | RF_Standalone);
	Texture->Source.Init(W, H, 1, 1, TSF_BGRA8, reinterpret_cast<const uint8*>(Pixels.GetData()));
	Texture->SRGB = true;
	Texture->CompressionSettings = TC_Default;
	Texture->LODGroup = TEXTUREGROUP_World;
	Texture->MipGenSettings = TMGS_FromTextureGroup;
	Texture->PostEditChange();
	Texture->UpdateResource();

	FAssetRegistryModule::AssetCreated(Texture);
	Texture->MarkPackageDirty();

	const FString PackageFilename = FPackageName::LongPackageNameToFilename(
		Package->GetName(), FPackageName::GetAssetPackageExtension());
	FSavePackageArgs SaveArgs;
	SaveArgs.TopLevelFlags = RF_Public | RF_Standalone;
	UPackage::SavePackage(Package, Texture, *PackageFilename, SaveArgs);
	return Texture;
#else
	return nullptr;
#endif
}

UMaterialInterface* UMapboxImporterConfig::GetOrGenerateMasterMaterial()
{
	if (UMaterialInterface* Set = LandscapeMasterMaterial.LoadSynchronous())
	{
		return Set;
	}
	if (!bAutoGenerateDefaultAssets)
	{
		return nullptr;
	}
#if WITH_EDITOR
	TArray<FName> Names;
	for (const FMapboxLayerDef& L : MapboxLayers) { Names.Add(L.LayerName); }
	return MapboxAssetGenerator::GetOrCreateDefaultMasterMaterial(Names);
#else
	return nullptr;
#endif
}

UMaterialInstanceConstant* UMapboxImporterConfig::CreateMaterialInstanceForChunk(
	UMaterialInterface* Master, UTexture2D* SatelliteTexture, int32 ChunkX, int32 ChunkY,
	FVector LandscapeOriginCm, double LandscapeWorldSizeCm) const
{
#if WITH_EDITOR
	if (!Master) return nullptr;

	const FString AssetName = FString::Printf(TEXT("MI_MapboxLandscape_C%d_%d"), ChunkX, ChunkY);
	const FString PackagePath = FString::Printf(TEXT("/Game/MapboxLandscape/MaterialInstances/%s"), *AssetName);

	UPackage* Package = CreatePackage(*PackagePath);
	if (!Package) return nullptr;
	Package->FullyLoad();

	// If an instance with this name already exists from a prior fetch, overwrite its parameter values instead of creating a duplicate.
	UMaterialInstanceConstant* MIC = FindObject<UMaterialInstanceConstant>(Package, *AssetName);
	if (!MIC)
	{
		UMaterialInstanceConstantFactoryNew* Factory = NewObject<UMaterialInstanceConstantFactoryNew>();
		Factory->InitialParent = Master;
		MIC = Cast<UMaterialInstanceConstant>(Factory->FactoryCreateNew(
			UMaterialInstanceConstant::StaticClass(), Package, *AssetName, RF_Public | RF_Standalone, nullptr, GWarn));
		if (MIC)
		{
			FAssetRegistryModule::AssetCreated(MIC);
		}
	}
	else
	{
		MIC->SetParentEditorOnly(Master);
	}

	if (!MIC) return nullptr;

	if (SatelliteTexture)
	{
		MIC->SetTextureParameterValueEditorOnly(FMaterialParameterInfo(TEXT("SatelliteTexture")), SatelliteTexture);
		MIC->SetScalarParameterValueEditorOnly(FMaterialParameterInfo(TEXT("SatelliteStrength")),
			SatelliteMode == EMapboxSatelliteMode::BlendIntoMaterial ? 1.f : 0.f);
	}

	// UV mapping: BaseColor UVs are (WorldPos.xy - LandscapeOrigin.xy) / LandscapeWorldSize.
	// Stash the chunk's world XY origin and side length so the master's WorldPosition graph maps the texture exactly once.
	MIC->SetVectorParameterValueEditorOnly(FMaterialParameterInfo(TEXT("LandscapeOrigin")),
		FLinearColor((float)LandscapeOriginCm.X, (float)LandscapeOriginCm.Y, 0.f, 0.f));
	MIC->SetScalarParameterValueEditorOnly(FMaterialParameterInfo(TEXT("LandscapeWorldSize")),
		(float)LandscapeWorldSizeCm);

	for (const FMapboxLayerDef& L : MapboxLayers)
	{
		const FName Param(*FString::Printf(TEXT("%s_Tint"), *L.LayerName.ToString()));
		MIC->SetVectorParameterValueEditorOnly(FMaterialParameterInfo(Param), L.MaterialTint);
	}

	MIC->PreEditChange(nullptr);
	MIC->PostEditChange();
	MIC->MarkPackageDirty();

	const FString Filename = FPackageName::LongPackageNameToFilename(Package->GetName(), FPackageName::GetAssetPackageExtension());
	FSavePackageArgs SaveArgs;
	SaveArgs.TopLevelFlags = RF_Public | RF_Standalone;
	UPackage::SavePackage(Package, MIC, *Filename, SaveArgs);

	UE_LOG(LogMapbox, Log, TEXT("Mapbox: MIC %s, origin=(%.0f, %.0f) size=%.0fcm%s"),
		*PackagePath, LandscapeOriginCm.X, LandscapeOriginCm.Y, LandscapeWorldSizeCm,
		SatelliteTexture ? TEXT("") : TEXT(" [no satellite]"));
	return MIC;
#else
	return nullptr;
#endif
}

UPCGGraphInterface* UMapboxImporterConfig::GetOrGenerateScatterGraph()
{
	if (UPCGGraphInterface* Set = ScatterPCGGraph.LoadSynchronous())
	{
		return Set;
	}
	if (!bAutoGenerateDefaultAssets)
	{
		return nullptr;
	}
#if WITH_EDITOR
	return MapboxAssetGenerator::GetOrCreateDefaultScatterGraph();
#else
	return nullptr;
#endif
}

// ----- Main processing -------------------------------------------------------

static void ResampleHeights(const TArray<float>& Src, int32 SrcW, int32 SrcH,
                             TArray<float>& Dst, int32 DstW, int32 DstH)
{
	Dst.SetNumUninitialized(DstW * DstH);
	const float SX = (float)(SrcW - 1) / FMath::Max(1, DstW - 1);
	const float SY = (float)(SrcH - 1) / FMath::Max(1, DstH - 1);
	for (int32 y = 0; y < DstH; ++y)
	{
		const float fy = y * SY;
		const int32 y0 = FMath::FloorToInt(fy);
		const int32 y1 = FMath::Min(y0 + 1, SrcH - 1);
		const float ty = fy - y0;
		for (int32 x = 0; x < DstW; ++x)
		{
			const float fx = x * SX;
			const int32 x0 = FMath::FloorToInt(fx);
			const int32 x1 = FMath::Min(x0 + 1, SrcW - 1);
			const float tx = fx - x0;
			const float A = Src[y0 * SrcW + x0];
			const float B = Src[y0 * SrcW + x1];
			const float C = Src[y1 * SrcW + x0];
			const float D = Src[y1 * SrcW + x1];
			const float AB = FMath::Lerp(A, B, tx);
			const float CD = FMath::Lerp(C, D, tx);
			Dst[y * DstW + x] = FMath::Lerp(AB, CD, ty);
		}
	}
}

static void ResampleColors(const TArray<FColor>& Src, int32 SrcW, int32 SrcH,
                            TArray<FColor>& Dst, int32 DstW, int32 DstH)
{
	Dst.SetNumUninitialized(DstW * DstH);
	const float SX = (float)SrcW / FMath::Max(1, DstW);
	const float SY = (float)SrcH / FMath::Max(1, DstH);
	for (int32 y = 0; y < DstH; ++y)
	{
		const int32 sy = FMath::Clamp((int32)(y * SY), 0, SrcH - 1);
		for (int32 x = 0; x < DstW; ++x)
		{
			const int32 sx = FMath::Clamp((int32)(x * SX), 0, SrcW - 1);
			Dst[y * DstW + x] = Src[sy * SrcW + sx];
		}
	}
}

static int32 PickValidLandscapeSize(int32 Desired, int32 SectionSize = 63)
{
	const int32 Components = FMath::Max(1, FMath::RoundToInt((float)(Desired - 1) / SectionSize));
	return Components * SectionSize + 1;
}

// ---------- MVT rasterization helpers ----------

// Stamps a filled square brush centered at (cx, cy) with given radius into the mask.
static FORCEINLINE void StampBrush(TArray<uint8>& Mask, int32 W, int32 H, int32 Cx, int32 Cy, int32 Radius)
{
	const int32 X0 = FMath::Clamp(Cx - Radius, 0, W - 1);
	const int32 X1 = FMath::Clamp(Cx + Radius, 0, W - 1);
	const int32 Y0 = FMath::Clamp(Cy - Radius, 0, H - 1);
	const int32 Y1 = FMath::Clamp(Cy + Radius, 0, H - 1);
	for (int32 Y = Y0; Y <= Y1; ++Y)
	{
		uint8* Row = Mask.GetData() + Y * W;
		for (int32 X = X0; X <= X1; ++X)
		{
			Row[X] = 255;
		}
	}
}

// Bresenham line with thickness (brush radius). Coordinates are mask pixels.
static void RasterLine(TArray<uint8>& Mask, int32 W, int32 H,
                        int32 X0, int32 Y0, int32 X1, int32 Y1, int32 BrushRadius)
{
	int32 Dx = FMath::Abs(X1 - X0);
	int32 Dy = -FMath::Abs(Y1 - Y0);
	int32 Sx = X0 < X1 ? 1 : -1;
	int32 Sy = Y0 < Y1 ? 1 : -1;
	int32 Err = Dx + Dy;
	int32 X = X0, Y = Y0;
	while (true)
	{
		StampBrush(Mask, W, H, X, Y, BrushRadius);
		if (X == X1 && Y == Y1) break;
		const int32 E2 = 2 * Err;
		if (E2 >= Dy) { Err += Dy; X += Sx; }
		if (E2 <= Dx) { Err += Dx; Y += Sy; }
	}
}

// Scanline polygon fill (even-odd rule). Handles multiple rings via separate calls + XOR semantics.
// Nearest-neighbor uint8 mask resampling.
static void ResampleMask(const TArray<uint8>& Src, int32 SrcW, int32 SrcH,
                          TArray<uint8>& Dst, int32 DstW, int32 DstH)
{
	Dst.SetNumZeroed(DstW * DstH);
	const float SX = (float)SrcW / FMath::Max(1, DstW);
	const float SY = (float)SrcH / FMath::Max(1, DstH);
	for (int32 y = 0; y < DstH; ++y)
	{
		const int32 sy = FMath::Clamp((int32)(y * SY), 0, SrcH - 1);
		for (int32 x = 0; x < DstW; ++x)
		{
			const int32 sx = FMath::Clamp((int32)(x * SX), 0, SrcW - 1);
			Dst[y * DstW + x] = Src[sy * SrcW + sx];
		}
	}
}

static void RasterPolygonRing(TArray<uint8>& Mask, int32 W, int32 H, const TArray<FVector2D>& Ring)
{
	if (Ring.Num() < 3) return;

	int32 MinY = FMath::FloorToInt(Ring[0].Y);
	int32 MaxY = MinY;
	for (const FVector2D& P : Ring)
	{
		MinY = FMath::Min(MinY, FMath::FloorToInt(P.Y));
		MaxY = FMath::Max(MaxY, FMath::CeilToInt(P.Y));
	}
	MinY = FMath::Clamp(MinY, 0, H - 1);
	MaxY = FMath::Clamp(MaxY, 0, H - 1);

	TArray<float> XIntersections;
	XIntersections.Reserve(Ring.Num());

	for (int32 Y = MinY; Y <= MaxY; ++Y)
	{
		const float Fy = (float)Y + 0.5f;
		XIntersections.Reset();

		for (int32 i = 0, j = Ring.Num() - 1; i < Ring.Num(); j = i++)
		{
			const FVector2D& A = Ring[j];
			const FVector2D& B = Ring[i];
			if ((A.Y <= Fy && B.Y > Fy) || (B.Y <= Fy && A.Y > Fy))
			{
				const float T = (Fy - A.Y) / (B.Y - A.Y);
				XIntersections.Add(A.X + T * (B.X - A.X));
			}
		}

		XIntersections.Sort();
		for (int32 i = 0; i + 1 < XIntersections.Num(); i += 2)
		{
			const int32 X0 = FMath::Clamp(FMath::FloorToInt(XIntersections[i]), 0, W - 1);
			const int32 X1 = FMath::Clamp(FMath::CeilToInt(XIntersections[i + 1]), 0, W - 1);
			uint8* Row = Mask.GetData() + Y * W;
			for (int32 X = X0; X <= X1; ++X)
			{
				Row[X] = 255;
			}
		}
	}
}

void UMapboxImporterConfig::OnAllTilesDownloaded()
{
	// Compute global min elevation across all height tiles for a shared baseline.
	float GlobalMin = FLT_MAX;
	float GlobalMax = -FLT_MAX;

	for (int32 X = MinTileX; X <= MaxTileX; ++X)
	{
		for (int32 Y = MinTileY; Y <= MaxTileY; ++Y)
		{
			FTileBlob* Blob = CompletedBlobs.Find(KeyFor(X, Y, ETileKind::Height));
			if (!Blob || !Blob->bOk) continue;
			TArray<uint8> RGBA; int32 W = 0, H = 0;
			if (!DecodeTileToRGBA(Blob->Bytes, RGBA, W, H)) continue;
			const int32 Pixels = W * H;
			for (int32 i = 0; i < Pixels; ++i)
			{
				const float M = DecodeHeightMeters(RGBA[i * 4 + 0], RGBA[i * 4 + 1], RGBA[i * 4 + 2]);
				if (M < GlobalMin) GlobalMin = M;
				if (M > GlobalMax) GlobalMax = M;
			}
		}
	}
	if (GlobalMin == FLT_MAX) { GlobalMin = 0.f; GlobalMax = 0.f; }
	const float BaselineMeters = bRebaseToSeaLevel ? 0.f : GlobalMin;
	const float RangeMeters = FMath::Max(50.f, (GlobalMax - BaselineMeters) * ZExaggeration + 1.f);
	UE_LOG(LogMapbox, Log, TEXT("Mapbox: elevation min=%.1fm max=%.1fm baseline=%.1f range=%.1f"),
		GlobalMin, GlobalMax, BaselineMeters, RangeMeters);

	// Compute landscape Z scale so that GlobalMax fits within ±256m * (ZScale/100).
	// HeightValue = (Meters - Baseline) * ZExaggeration * (100 / ZScale_factor) * 128/100 + 32768
	// We want max HeightValue = 65535. Solve: ZScale = ceil((MaxMeters - Baseline) * ZExaggeration * 128 / 32767) * 100
	const float LandscapeZScale = FMath::Max(100.f, RangeMeters * 100.f * 128.f / 32767.f);
	UE_LOG(LogMapbox, Log, TEXT("Mapbox: chosen landscape Z scale = %.2f"), LandscapeZScale);

	const double CenterLat = (TileYToLat(MinTileY, ResolvedZoom) + TileYToLat(MaxTileY + 1, ResolvedZoom)) * 0.5;
	const double TileSideMeters = MetersPerTileSide(CenterLat, ResolvedZoom);
	const double WorldCmPerSourcePixel = (TileSideMeters / 256.0) * 100.0; // cm/source-pixel
	const double TileWorldCm = 256.0 * WorldCmPerSourcePixel;
	const int32 TilesXAll = MaxTileX - MinTileX + 1;
	const int32 TilesYAll = MaxTileY - MinTileY + 1;
	const double TotalWorldX = TilesXAll * TileWorldCm;
	const double TotalWorldY = TilesYAll * TileWorldCm;

	// Process each chunk
	GeneratedLandscapes.Reset();

	for (const FLandscapeChunk& Chunk : Chunks)
	{
		const int32 SrcW = Chunk.TilesX * 256;
		const int32 SrcH = Chunk.TilesY * 256;

		TArray<float> SrcHeightsMeters; SrcHeightsMeters.SetNumZeroed(SrcW * SrcH);
		TArray<FColor> SrcMetadata; SrcMetadata.SetNumZeroed(SrcW * SrcH);
		TArray<FColor> SrcSatellite; SrcSatellite.SetNumZeroed(SrcW * SrcH);

		bool bMissing = false;
		for (int32 ty = 0; ty < Chunk.TilesY; ++ty)
		{
			for (int32 tx = 0; tx < Chunk.TilesX; ++tx)
			{
				const int32 TileX = Chunk.MinTileX + tx;
				const int32 TileY = Chunk.MinTileY + ty;
				const int32 BaseX = tx * 256;
				const int32 BaseY = ty * 256;

				// Height
				{
					FTileBlob* Blob = CompletedBlobs.Find(KeyFor(TileX, TileY, ETileKind::Height));
					TArray<uint8> RGBA; int32 W = 0, H = 0;
					if (Blob && Blob->bOk && DecodeTileToRGBA(Blob->Bytes, RGBA, W, H) && W == 256 && H == 256)
					{
						for (int32 py = 0; py < 256; ++py)
						for (int32 px = 0; px < 256; ++px)
						{
							const int32 i = (py * 256 + px) * 4;
							SrcHeightsMeters[(BaseY + py) * SrcW + (BaseX + px)] =
								DecodeHeightMeters(RGBA[i], RGBA[i + 1], RGBA[i + 2]);
						}
					}
					else { bMissing = true; }
				}

				// Metadata
				{
					FTileBlob* Blob = CompletedBlobs.Find(KeyFor(TileX, TileY, ETileKind::Metadata));
					TArray<uint8> RGBA; int32 W = 0, H = 0;
					if (Blob && Blob->bOk && DecodeTileToRGBA(Blob->Bytes, RGBA, W, H) && W == 256 && H == 256)
					{
						for (int32 py = 0; py < 256; ++py)
						for (int32 px = 0; px < 256; ++px)
						{
							const int32 i = (py * 256 + px) * 4;
							SrcMetadata[(BaseY + py) * SrcW + (BaseX + px)] =
								FColor(RGBA[i], RGBA[i + 1], RGBA[i + 2], 255);
						}
					}
				}

				// Satellite
				if (SatelliteMode != EMapboxSatelliteMode::None)
				{
					FTileBlob* Blob = CompletedBlobs.Find(KeyFor(TileX, TileY, ETileKind::Satellite));
					TArray<uint8> RGBA; int32 W = 0, H = 0;
					if (Blob && Blob->bOk && DecodeTileToRGBA(Blob->Bytes, RGBA, W, H) && W == 256 && H == 256)
					{
						for (int32 py = 0; py < 256; ++py)
						for (int32 px = 0; px < 256; ++px)
						{
							const int32 i = (py * 256 + px) * 4;
							// Source RGBA -> stored as FColor in BGRA layout
							SrcSatellite[(BaseY + py) * SrcW + (BaseX + px)] =
								FColor(RGBA[i + 2], RGBA[i + 1], RGBA[i + 0], 255);
						}
					}
				}
			}
		}

		if (bMissing)
		{
			UE_LOG(LogMapbox, Warning, TEXT("Mapbox: chunk (%d,%d) has missing height tiles, expect gaps."),
				Chunk.ChunkX, Chunk.ChunkY);
		}

		const int32 LandscapeVerts = PickValidLandscapeSize(SrcW);

		// Resample to landscape resolution
		TArray<float> ResampledHeights;
		ResampleHeights(SrcHeightsMeters, SrcW, SrcH, ResampledHeights, LandscapeVerts, LandscapeVerts);

		TArray<FColor> ResampledMeta;
		ResampleColors(SrcMetadata, SrcW, SrcH, ResampledMeta, LandscapeVerts, LandscapeVerts);

		// Build heightmap uint16 with chosen baseline + Z scale
		TArray<uint16> Heightmap; Heightmap.SetNumUninitialized(LandscapeVerts * LandscapeVerts);
		const float Numerator = 100.f * 128.f * ZExaggeration; // (cm/m) * heightmap_units/cm normalized * exaggeration
		for (int32 i = 0; i < ResampledHeights.Num(); ++i)
		{
			const float WorldZcm = (ResampledHeights[i] - BaselineMeters) * 100.f * ZExaggeration;
			const float Val = WorldZcm * 128.f / FMath::Max(LandscapeZScale, 1.f) + 32768.f;
			Heightmap[i] = (uint16)FMath::Clamp(FMath::RoundToInt(Val), 0, 65535);
		}

		// Rasterize matching MVT features into source-resolution per-layer masks.
		// SrcVectorMasks[i] is populated only for layers whose MatchMode != Color.
		TArray<TArray<uint8>> SrcVectorMasks;
		SrcVectorMasks.SetNum(MapboxLayers.Num());
		for (int32 i = 0; i < MapboxLayers.Num(); ++i)
		{
			if (MapboxLayers[i].MatchMode != EMapboxLayerMatchMode::Color && !MapboxLayers[i].VectorFilters.IsEmpty())
			{
				SrcVectorMasks[i].SetNumZeroed(SrcW * SrcH);
			}
		}

		if (LayersNeedVectorTiles(MapboxLayers))
		{
			const double MetersPerSrcPixel = TileSideMeters / 256.0;
			for (int32 ty = 0; ty < Chunk.TilesY; ++ty)
			for (int32 tx = 0; tx < Chunk.TilesX; ++tx)
			{
				const int32 TileX = Chunk.MinTileX + tx;
				const int32 TileY = Chunk.MinTileY + ty;
				const int32 BaseX = tx * 256;
				const int32 BaseY = ty * 256;

				FTileBlob* Blob = CompletedBlobs.Find(KeyFor(TileX, TileY, ETileKind::Vector));
				if (!Blob || !Blob->bOk) continue;

				TArray<MapboxMvt::FLayer> MvtLayers;
				if (!MapboxMvt::ParseTile(Blob->Bytes, MvtLayers)) continue;

				for (const MapboxMvt::FLayer& MvtLayer : MvtLayers)
				{
					// For each of our config layers using vector matching, check filters
					for (int32 LayerIdx = 0; LayerIdx < MapboxLayers.Num(); ++LayerIdx)
					{
						const FMapboxLayerDef& L = MapboxLayers[LayerIdx];
						if (L.MatchMode == EMapboxLayerMatchMode::Color) continue;

						for (const FMapboxVectorFeatureFilter& Filter : L.VectorFilters)
						{
							if (!Filter.MvtLayer.Equals(MvtLayer.Name, ESearchCase::IgnoreCase)) continue;

							const float ExtentToPixels = 256.f / FMath::Max(1.f, (float)MvtLayer.Extent);
							const int32 BrushRadius = FMath::Max(0,
								FMath::CeilToInt(Filter.LineWidthMeters / FMath::Max(MetersPerSrcPixel, 0.01) / 2.0));

							for (const MapboxMvt::FFeature& Feature : MvtLayer.Features)
							{
								if (!MapboxMvt::FeatureMatchesClass(Feature, Filter.Classes)) continue;

								if (Feature.Type == MapboxMvt::EFeatureType::LineString)
								{
									for (const TArray<FVector2D>& Line : Feature.Geometry)
									{
										if (Line.Num() < 2) continue;
										int32 PrevX = BaseX + (int32)(Line[0].X * ExtentToPixels);
										int32 PrevY = BaseY + (int32)(Line[0].Y * ExtentToPixels);
										for (int32 p = 1; p < Line.Num(); ++p)
										{
											const int32 CurX = BaseX + (int32)(Line[p].X * ExtentToPixels);
											const int32 CurY = BaseY + (int32)(Line[p].Y * ExtentToPixels);
											RasterLine(SrcVectorMasks[LayerIdx], SrcW, SrcH, PrevX, PrevY, CurX, CurY, BrushRadius);
											PrevX = CurX; PrevY = CurY;
										}
									}
								}
								else if (Feature.Type == MapboxMvt::EFeatureType::Polygon)
								{
									for (const TArray<FVector2D>& Ring : Feature.Geometry)
									{
										TArray<FVector2D> Transformed;
										Transformed.Reserve(Ring.Num());
										for (const FVector2D& P : Ring)
										{
											Transformed.Add(FVector2D(BaseX + P.X * ExtentToPixels,
												BaseY + P.Y * ExtentToPixels));
										}
										RasterPolygonRing(SrcVectorMasks[LayerIdx], SrcW, SrcH, Transformed);
									}
								}
							}
						}
					}
				}
			}
		}

		// Resample SrcVectorMasks down to landscape resolution
		TArray<TArray<uint8>> ResampledVectorMasks;
		ResampledVectorMasks.SetNum(MapboxLayers.Num());
		for (int32 i = 0; i < MapboxLayers.Num(); ++i)
		{
			if (SrcVectorMasks[i].Num() > 0)
			{
				ResampleMask(SrcVectorMasks[i], SrcW, SrcH, ResampledVectorMasks[i], LandscapeVerts, LandscapeVerts);
			}
		}

		// Build per-layer weightmaps with priority-based merge of color and vector matches.
		TMap<FName, TArray<uint8>> LayerWeights;
		for (const FMapboxLayerDef& L : MapboxLayers)
		{
			LayerWeights.Add(L.LayerName).SetNumZeroed(LandscapeVerts * LandscapeVerts);
		}

		const int32 PixelCount = LandscapeVerts * LandscapeVerts;
		TArray<int32> WinnerLayer; WinnerLayer.Init(INDEX_NONE, PixelCount);
		TArray<int32> WinnerPriority; WinnerPriority.Init(-1, PixelCount);

		// Color candidates
		for (int32 i = 0; i < PixelCount; ++i)
		{
			const int32 ColorIdx = ClassifyPixel(ResampledMeta[i]);
			if (ColorIdx != INDEX_NONE)
			{
				const FMapboxLayerDef& L = MapboxLayers[ColorIdx];
				if (L.MatchMode != EMapboxLayerMatchMode::Vector && L.Priority > WinnerPriority[i])
				{
					WinnerPriority[i] = L.Priority;
					WinnerLayer[i] = ColorIdx;
				}
			}
		}

		// Vector candidates
		for (int32 LayerIdx = 0; LayerIdx < MapboxLayers.Num(); ++LayerIdx)
		{
			const TArray<uint8>& M = ResampledVectorMasks[LayerIdx];
			if (M.Num() == 0) continue;
			const FMapboxLayerDef& L = MapboxLayers[LayerIdx];
			for (int32 i = 0; i < PixelCount; ++i)
			{
				if (M[i] >= 128 && L.Priority > WinnerPriority[i])
				{
					WinnerPriority[i] = L.Priority;
					WinnerLayer[i] = LayerIdx;
				}
			}
		}

		// Write winners to layer weight maps
		for (int32 i = 0; i < PixelCount; ++i)
		{
			if (WinnerLayer[i] != INDEX_NONE)
			{
				LayerWeights[MapboxLayers[WinnerLayer[i]].LayerName][i] = 255;
			}
		}

		// Satellite texture asset
		UTexture2D* SatTexture = nullptr;
		if (SatelliteMode != EMapboxSatelliteMode::None)
		{
			TArray<FColor> ResampledSat;
			ResampleColors(SrcSatellite, SrcW, SrcH, ResampledSat, LandscapeVerts, LandscapeVerts);
			const FString AssetName = FString::Printf(TEXT("T_MapboxSat_C%d_%d_Z%d"),
				Chunk.ChunkX, Chunk.ChunkY, ResolvedZoom);
			SatTexture = SaveTransientToAsset(ResampledSat, LandscapeVerts, LandscapeVerts, AssetName);
		}

		const double WorldSizePerLandscapeCm = SrcW * WorldCmPerSourcePixel;
		ALandscape* Landscape = SpawnLandscapeForChunk(
			Chunk, Heightmap, LayerWeights, SatTexture,
			(double)LandscapeVerts, WorldSizePerLandscapeCm, LandscapeZScale,
			TileWorldCm, TotalWorldX, TotalWorldY);

		if (Landscape)
		{
			FMapboxTileResult R; R.TileGridX = Chunk.ChunkX; R.TileGridY = Chunk.ChunkY; R.Landscape = Landscape;
			GeneratedLandscapes.Add(R);

			SpawnPCGForLandscape(Landscape, SatTexture, LayerWeights, LandscapeVerts, WorldSizePerLandscapeCm);
			SpawnSatelliteDecal(Landscape, SatTexture, WorldSizePerLandscapeCm);
		}
	}

	UE_LOG(LogMapbox, Log, TEXT("Mapbox: created %d landscape actor(s)."), GeneratedLandscapes.Num());
	if (GeneratedLandscapes.Num() > 0)
	{
		MapboxUI::Notify(MapboxUI::ESeverity::Success,
			FString::Printf(TEXT("Mapbox: created %d landscape actor(s)."), GeneratedLandscapes.Num()));
	}
	else
	{
		MapboxUI::Notify(MapboxUI::ESeverity::Warning,
			TEXT("Mapbox: fetch finished but no landscapes were created."),
			TEXT("Check the Output Log for per-tile errors (often HTTP 401 = invalid token, or 404 = wrong style ID)."),
			/*bModal=*/true);
	}
	FinishFetch();
}

ALandscape* UMapboxImporterConfig::SpawnLandscapeForChunk(const FLandscapeChunk& Chunk,
	const TArray<uint16>& HeightData,
	const TMap<FName, TArray<uint8>>& LayerWeights,
	UTexture2D* SatelliteTexture,
	double LandscapeVertsPerSide,
	double WorldSizePerLandscapeCm,
	double LandscapeZScale,
	double TileWorldCm,
	double TotalWorldX,
	double TotalWorldY)
{
	UWorld* World = GetWorld();
	if (!World) return nullptr;

	const int32 SectionSize = 63;
	const int32 SectionsPerComponent = 1;
	const int32 Verts = (int32)LandscapeVertsPerSide;
	const int32 ComponentsPerSide = (Verts - 1) / SectionSize;

	FActorSpawnParameters Params;
	Params.Name = MakeUniqueObjectName(World->PersistentLevel, ALandscape::StaticClass(),
		*FString::Printf(TEXT("MapboxLandscape_C%d_%d"), Chunk.ChunkX, Chunk.ChunkY));
	ALandscape* Landscape = World->SpawnActor<ALandscape>(ALandscape::StaticClass(), Params);
	if (!Landscape) return nullptr;

	Landscape->SetActorLabel(FString::Printf(TEXT("MapboxLandscape_C%d_%d"), Chunk.ChunkX, Chunk.ChunkY));

	// Position chunk by its actual tile offset (handles uneven trailing chunks correctly)
	// and center the whole area on the actor's pivot.
	const double XYScale = WorldSizePerLandscapeCm / (LandscapeVertsPerSide - 1);
	const double LocalX = (Chunk.MinTileX - MinTileX) * TileWorldCm - TotalWorldX * 0.5;
	const double LocalY = (Chunk.MinTileY - MinTileY) * TileWorldCm - TotalWorldY * 0.5;
	const FVector ChunkOrigin = ImportOrigin + FVector(LocalX, LocalY, 0.0);
	Landscape->SetActorTransform(FTransform(FRotator::ZeroRotator, ChunkOrigin,
		FVector(XYScale, XYScale, LandscapeZScale)));

	// Material — use a saved UMaterialInstanceConstant (not UMaterialInstanceDynamic) so it
	// persists across editor restarts and gets properly shader-compiled before we use it.
	UMaterialInterface* Master = GetOrGenerateMasterMaterial();
	if (!Master)
	{
		UE_LOG(LogMapbox, Warning, TEXT("Mapbox: no master material available (auto-gen disabled or failed). Landscape will use the default checker material."));
	}
	else if (SatelliteMode == EMapboxSatelliteMode::BlendIntoMaterial)
	{
		UMaterialInstanceConstant* MIC = CreateMaterialInstanceForChunk(Master, SatelliteTexture,
			Chunk.ChunkX, Chunk.ChunkY, ChunkOrigin, WorldSizePerLandscapeCm);
		Landscape->LandscapeMaterial = MIC ? Cast<UMaterialInterface>(MIC) : Master;
	}
	else
	{
		// SatelliteMode = None or OverlayDecal — bind master directly (decal is handled separately below).
		Landscape->LandscapeMaterial = Master;
	}

	// Import height + layer data
#if WITH_EDITOR
	const FGuid LandscapeGuid = FGuid::NewGuid();
	TMap<FGuid, TArray<uint16>> HeightDataPerLayers;
	HeightDataPerLayers.Add(FGuid(), HeightData); // keyed by default GUID = base layer

	TArray<FLandscapeImportLayerInfo> LayerInfos;
	for (const TPair<FName, TArray<uint8>>& Pair : LayerWeights)
	{
		FLandscapeImportLayerInfo Info;
		Info.LayerName = Pair.Key;
		Info.LayerInfo = NewObject<ULandscapeLayerInfoObject>(Landscape, Pair.Key);
		Info.LayerInfo->SetLayerName(Pair.Key, /*bInModify=*/false);
		Info.LayerData = Pair.Value;

		// Try to assign physical material from layer def
		for (const FMapboxLayerDef& L : MapboxLayers)
		{
			if (L.LayerName == Pair.Key)
			{
				if (UPhysicalMaterial* PM = L.PhysicalMaterial.LoadSynchronous())
				{
					Info.LayerInfo->SetPhysicalMaterial(PM, /*bInModify=*/false);
				}
				break;
			}
		}
		LayerInfos.Add(Info);
	}
	TMap<FGuid, TArray<FLandscapeImportLayerInfo>> MaterialLayerDataPerLayers;
	MaterialLayerDataPerLayers.Add(FGuid(), LayerInfos);

	Landscape->Import(
		LandscapeGuid,
		0, 0,
		Verts - 1, Verts - 1,
		SectionsPerComponent, SectionSize,
		HeightDataPerLayers,
		TEXT(""),
		MaterialLayerDataPerLayers,
		ELandscapeImportAlphamapType::Additive,
		TArrayView<const FLandscapeLayer>());

	Landscape->StaticLightingLOD = (int8)FMath::DivideAndRoundUp(
		(int32)FMath::CeilLogTwo((Verts * Verts) / (2048 * 2048) + 1), 2);

	ULandscapeInfo* LandscapeInfo = Landscape->CreateLandscapeInfo();
	if (LandscapeInfo)
	{
		LandscapeInfo->UpdateLayerInfoMap(Landscape);
	}

	// Force the landscape and its components to pick up the assigned material now.
	Landscape->PostEditChange();
	Landscape->ReregisterAllComponents();
#endif

	return Landscape;
}

// ----- PCG / HISM scatter ---------------------------------------------------

static FVector SampleLandscapeHeight(ALandscape* Landscape, double WorldX, double WorldY)
{
	if (!Landscape) return FVector(WorldX, WorldY, 0.0);
	const FVector Origin = Landscape->GetActorLocation();
	const FVector Scale = Landscape->GetActorScale3D();
	// Approximation: use the landscape's collision component height query via line trace.
	UWorld* World = Landscape->GetWorld();
	if (!World) return FVector(WorldX, WorldY, Origin.Z);
	FHitResult Hit;
	const FVector Start(WorldX, WorldY, Origin.Z + 100000.f);
	const FVector End(WorldX, WorldY, Origin.Z - 100000.f);
	FCollisionQueryParams P;
	if (World->LineTraceSingleByChannel(Hit, Start, End, ECC_WorldStatic, P))
	{
		return Hit.ImpactPoint;
	}
	return FVector(WorldX, WorldY, Origin.Z);
}

void UMapboxImporterConfig::SpawnPCGForLandscape(ALandscape* Landscape, UTexture2D* /*SatelliteTexture*/,
	const TMap<FName, TArray<uint8>>& LayerWeights, int32 LandscapeVerts, double WorldSizePerLandscapeCm)
{
	if (!Landscape) return;

	// PCG path: spawn a component with the user's (or auto-generated) graph and let it handle scatter.
	UPCGGraphInterface* Graph = bSpawnPCGComponents ? GetOrGenerateScatterGraph() : nullptr;
	if (Graph)
	{
		UPCGComponent* PCG = NewObject<UPCGComponent>(Landscape, UPCGComponent::StaticClass(),
			TEXT("MapboxScatterPCG"), RF_Transactional);
		if (PCG)
		{
			Landscape->AddInstanceComponent(PCG);
			PCG->RegisterComponent();
			PCG->SetGraph(Graph);
			PCG->GenerationTrigger = EPCGComponentGenerationTrigger::GenerateOnLoad;
			PCG->Generate(true);
			// Continue and also do HISM as a baseline; user can disable HISM by emptying meshes once their PCG graph is wired up.
		}
	}

	// HISM scatter — respects per-layer weight maps so trees only land on forest, etc.
	const FVector LandscapeOrigin = Landscape->GetActorLocation();
	const double CmPerVert = WorldSizePerLandscapeCm / FMath::Max(1, LandscapeVerts - 1);

	for (const FMapboxLayerDef& L : MapboxLayers)
	{
		if (!L.bScatterEnabled || L.ScatterMeshes.Num() == 0) continue;
		const TArray<uint8>* WeightsPtr = LayerWeights.Find(L.LayerName);
		if (!WeightsPtr || WeightsPtr->IsEmpty()) continue;
		const TArray<uint8>& Weights = *WeightsPtr;

		// One HISM component per unique mesh in the layer's array.
		TMap<UStaticMesh*, UHierarchicalInstancedStaticMeshComponent*> HISMs;
		for (const TSoftObjectPtr<UStaticMesh>& MeshRef : L.ScatterMeshes)
		{
			UStaticMesh* Mesh = MeshRef.LoadSynchronous();
			if (!Mesh || HISMs.Contains(Mesh)) continue;
			UHierarchicalInstancedStaticMeshComponent* HISM =
				NewObject<UHierarchicalInstancedStaticMeshComponent>(Landscape,
					MakeUniqueObjectName(Landscape, UHierarchicalInstancedStaticMeshComponent::StaticClass(),
						*FString::Printf(TEXT("HISM_%s_%s"), *L.LayerName.ToString(), *Mesh->GetName())),
					RF_Transactional);
			if (!HISM) continue;
			HISM->SetStaticMesh(Mesh);
			HISM->SetMobility(EComponentMobility::Static);
			HISM->SetupAttachment(Landscape->GetRootComponent());
			HISM->RegisterComponent();
			Landscape->AddInstanceComponent(HISM);
			HISMs.Add(Mesh, HISM);
		}
		if (HISMs.IsEmpty()) continue;

		TArray<UStaticMesh*> MeshOptions;
		HISMs.GetKeys(MeshOptions);

		// One sample per N landscape verts, where N ~ 100 / density (lower density = wider spacing).
		const float Density = FMath::Max(0.01f, L.ScatterDensity);
		const int32 SampleStride = FMath::Max(1, (int32)FMath::FloorToInt(10.f / Density));
		FRandomStream Rng((int32)(GetTypeHash(L.LayerName) ^ GetTypeHash((void*)Landscape)));

		for (int32 vy = 0; vy < LandscapeVerts; vy += SampleStride)
		{
			for (int32 vx = 0; vx < LandscapeVerts; vx += SampleStride)
			{
				const uint8 W = Weights[vy * LandscapeVerts + vx];
				if (W < 128) continue; // require majority weight
				const double Jx = (vx + Rng.FRandRange(-0.4, 0.4)) * CmPerVert;
				const double Jy = (vy + Rng.FRandRange(-0.4, 0.4)) * CmPerVert;
				const double WorldX = LandscapeOrigin.X + Jx;
				const double WorldY = LandscapeOrigin.Y + Jy;
				const FVector Pos = SampleLandscapeHeight(Landscape, WorldX, WorldY);
				const float ScaleS = Rng.FRandRange(L.ScatterMinScale, L.ScatterMaxScale);
				const float Yaw = L.bRandomYaw ? Rng.FRandRange(0.f, 360.f) : 0.f;
				UStaticMesh* Pick = MeshOptions[Rng.RandRange(0, MeshOptions.Num() - 1)];
				FTransform T(FRotator(0.f, Yaw, 0.f), Pos, FVector(ScaleS));
				HISMs[Pick]->AddInstance(T, true);
			}
		}
	}
}

void UMapboxImporterConfig::SpawnSatelliteDecal(ALandscape* Landscape, UTexture2D* SatelliteTexture, double WorldSizePerLandscapeCm)
{
	if (SatelliteMode != EMapboxSatelliteMode::OverlayDecal) return;
	if (!Landscape || !SatelliteTexture) return;

	UWorld* World = Landscape->GetWorld();
	if (!World) return;

#if WITH_EDITOR
	UMaterialInterface* DecalMaster = MapboxAssetGenerator::GetOrCreateDefaultDecalMaterial();
	if (!DecalMaster)
	{
		UE_LOG(LogMapbox, Warning, TEXT("Mapbox: failed to create decal master material; skipping decal."));
		return;
	}

	UMaterialInstanceDynamic* MID = UMaterialInstanceDynamic::Create(DecalMaster, Landscape);
	if (!MID) return;
	MID->SetTextureParameterValue(TEXT("SatelliteTexture"), SatelliteTexture);

	FActorSpawnParameters Params;
	Params.Owner = Landscape;
	Params.Name = MakeUniqueObjectName(World->PersistentLevel, ADecalActor::StaticClass(),
		*FString::Printf(TEXT("MapboxSatelliteDecal_%s"), *Landscape->GetName()));
	ADecalActor* Decal = World->SpawnActor<ADecalActor>(ADecalActor::StaticClass(), Params);
	if (!Decal) return;
	Decal->SetActorLabel(FString::Printf(TEXT("MapboxSatelliteDecal_%s"), *Landscape->GetName()));

	// Position above the landscape footprint center. ADecalActor's component is already
	// pre-rotated (-90 pitch) so the default actor rotation projects straight down.
	const FBox Bounds = Landscape->GetComponentsBoundingBox(true);
	const FVector Center = Bounds.GetCenter();
	const double ProjectionDepth = FMath::Max(100000.0, Bounds.GetSize().Z + 50000.0);
	Decal->SetActorLocation(FVector(Center.X, Center.Y, Bounds.Max.Z + ProjectionDepth * 0.5));

	Decal->AttachToActor(Landscape, FAttachmentTransformRules::KeepWorldTransform);

	if (UDecalComponent* DC = Decal->GetDecal())
	{
		DC->DecalSize = FVector(ProjectionDepth * 0.5, WorldSizePerLandscapeCm * 0.5, WorldSizePerLandscapeCm * 0.5);
		DC->SetDecalMaterial(MID);
		DC->SortOrder = 0;
	}
#endif
}

void UMapboxImporterConfig::FinishFetch()
{
	bIsFetching = false;
	InFlightRequests = 0;
	PendingDownloadQueue.Reset();
	CompletedBlobs.Reset();
}
